name: CI Pipeline

on:
  push:
    branches:
      - '**'  # Runs on push to any branch
  pull_request:
    branches:
      - main  # Runs on PRs targeting the main branch

jobs:
  code-validation:
    name: Code Validation (Linting)
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'  # Skip this job on direct pushes to main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npx eslint 'src/**/*.{js,jsx,ts,tsx}'

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: code-validation
    if: github.event_name == 'pull_request'  # Only runs on PRs

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Check for test files
        id: check-tests
        run: |
          if [ "$(find src -type f -name '*.test.ts' -o -name '*.test.js' | wc -l)" -eq "0" ]; then
            echo "No test files found. Skipping unit tests."
            exit 0
          fi

      - name: Run tests
        if: steps.check-tests.outcome == 'success'
        run: npm test
