name: CI Pipeline

on:
  push:
    branches:
      - '**'       # Run on every push to any branch
  pull_request:
    branches:
      - '**'       # Run on every pull request to any branch

jobs:
  code-validation:
    name: Code Validation (Linting)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npx eslint 'src/**/*.{js,jsx,ts,tsx}'

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: code-validation
    if: github.ref == 'refs/heads/main'  # Only run this job on pushes to master

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
