name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  code-validation:
    name: Code Validation (Linting)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npx eslint 'src/**/*.{js,jsx,ts,tsx}'

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: code-validation

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
